name: Test Echo Setup
on:
  push:
    branches: [ "hotfix/echo-pipeline", "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Echo Action
        uses: ./.github/workflows/template  # Reference to the directory containing action.yml
