name: "test echo setup"

on:
  push:
    branches: [ "hotfix/echo-pipeline", "main" ]
    
jobs:
  job: 
    runs-on: ubuntu-latest
    steps:
      - name: Test echo
        uses: ./.github/workflow/template/
