name: "test echo setup"

on:
  push:
    branches: [ "hotfix/echo-pipeline", "main" ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/workflows/template/action.yml
