name: CI-CD Pipeline for Azure Web App - FYPprojectwebapp

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
    # paths:
    #   - .github/workflows/main.yml
  pull_request:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt' # Specify distribution

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_cb45db4fe6674d7ca1db2e50953b92d8 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_08ad1f4c10a94ffdb81208aef013179d }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_cb45db4fe6674d7ca1db2e50953b92d8 }}/repository/docker/richardkhy/webapp/general/richardkhy/webapp:${{ github.sha }}
          file: ./Dockerfile

  scan:
    runs-on: ubuntu-latest
    needs: [build_test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: ./.github/template/sonarcloud/
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Scan HTML file for vulnerabilities
        run: |
          # Example: Scan for security issues using a tool like retire.js
          npx retire --path src/test.html --outputformat json

  create_artifact:
    runs-on: ubuntu-latest
    needs: [build_test, scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Node JS
      # - name: Zip artifact for deployment
      #   run: zip release.zip ./* -r
      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: node-app
      #     path: release.zip

      # .NET
      # - name: Publish 
      #   run: dotnet publish -c Release -o $GITHUB_WORKSPACE/artifact

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: .net-app
      #     path: $GITHUB_WORKSPACE/artifact

  deploy_docker:
    needs: [build_test, scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.18.15

      - name: Docker Deploy
        uses: ./.github/template/docker/
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Needed to get PR information, if any
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  deploy_web:
    runs-on: ubuntu-latest
    needs: [build_test, scan, deploy_docker, create_artifact]
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        # with:
        #   name: .net-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_B5C6 }}
          tenant-id: ${{ secrets.AZURE_TENET_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_B5C6 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'FYPprojectwebapp'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_2ad6e0e114864b5abe6310761bb9ba8e }}
          images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_cb45db4fe6674d7ca1db2e50953b92d8 }}/repository/docker/richardkhy/webapp/general/richardkhy/webapp:${{ github.sha }}'
