name: CI-CD pipeline

on:
  push:

jobs:
  build-deploy:
    name: Build and deploy web app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: ./.github/template/sonarcloud/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Lighthouse scanner
        uses: ./.github/template/lighthouse/ # Reference to the directory for lighthouse
  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-test
