name: CI-CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy web app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        
  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-test
