name: CI-CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.5

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt' # Specify distribution

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '12'

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Run tests on HTML files
        run: |
          # Example: Validate HTML file
          npx htmlhint src

  scan:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: ./.github/template/sonarcloud/
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Scan HTML file for vulnerabilities
        run: |
          # Example: Scan for security issues using a tool like retire.js
          npx retire --path src/test.html --outputformat json

  deploy:
    runs-on: windows-latest
    needs: [test, build, scan]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E0C70E49CC1A49F6B284EF3C3E637CA3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_36003FE7623E4BD4B7429AF5C9EAD6F7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F362C3CBB7D44E45B89D250CE4B44E8E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fypprojectapp'
          slot-name: 'Production'
          package: .

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.18.15

      - name: Docker Deploy
        uses: ./.github/template/docker/
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Needed to get PR information, if any
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
