name: CI-CD Pipeline

# 1) Set up and build the app
# 2) scan said app
# 3) deploy via docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  #Start of build job: Build the web application
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt' # Specify distribution

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'	

      - name: Run tests
        run: npm test # under deploy job or test job????

  #Start of test job: Test that the web application is up to standard
  test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      #- name: Run Cucumber tests	 
       # run: 

  #Start of Scan job: Scan the code for any vulnerabilities or known CSV
  scan:
    runs-on: ubuntu-latest
    needs: [test,build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: SonarCloud Scan
        uses: ./.github/template/sonarcloud/
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  #Start of Deply Job: Deploy code via docker to Kubernetes	     
  deploy:
    needs: [test,build,scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.18.15

#     - name: Deploy to Kubernetes
#       env:
#          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#       run: |
#          echo "$KUBE_CONFIG_DATA" | base64 --decode > $HOME/.kube/config
#          kubectl apply -f k8s-deployment.yaml
      - name: Docker Deploy
        uses: ./.github/template/docker/
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Needed to get PR information, if any
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}	  
