name: Test Echo Setup
on:
  push:
    branches: "*" 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Echo Action
        uses: ./.github/template/echo/ # Reference to the directory for echo
      # - name: Run SonarCloud
      #   uses: ./.github/template/sonarcloud/ # Reference to sonarcloud directory, use crt+ / to uncomment
